export type AuthColorScheme = 'light' | 'dark';

/** Paleta auth — light: SaaS B2B accesible; dark: estilo anterior. */
export const AuthColors = {
  light: {
    background: '#F7F8FA',
    card: '#FFFFFF',
    surface: '#FFFFFF',
    text: '#1A202C',
    textSecondary: '#4A5568',
    textMuted: '#94A3B8',
    border: '#E5E7EB',
    primary: '#3182CE',
    primaryPressed: '#2B6CB0',
    primaryText: '#FFFFFF',
    brandLogi: '#1A202C',
    brandTrack: '#3182CE',
    secondary: '#FFFFFF',
    secondaryText: '#1A202C',
    secondaryBorder: '#E2E8F0',
    error: '#DC2626',
    errorBg: '#FEF2F2',
    inputBg: '#F9FAFB',
    inputBorder: '#E5E7EB',
    link: '#3182CE',
    icon: '#1A202C',
    logoRing: 'transparent',
    tagline: '#718096',
  },
  dark: {
    background: '#0A0E1A',
    card: '#151B2B',
    surface: '#151B2B',
    text: '#F8FAFC',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    border: '#1E293B',
    primary: '#F8FAFC',
    primaryPressed: '#E2E8F0',
    primaryText: '#0A0E1A',
    brandLogi: '#F8FAFC',
    brandTrack: '#93C5FD',
    secondary: '#151B2B',
    secondaryText: '#F8FAFC',
    secondaryBorder: '#334155',
    error: '#F87171',
    errorBg: '#450A0A',
    inputBg: '#151B2B',
    inputBorder: '#1E293B',
    link: '#93C5FD',
    icon: '#F8FAFC',
    logoRing: '#1E293B',
    tagline: '#64748B',
  },
} as const;

export const AuthSpacing = {
  screenPadding: 20,
  screenPaddingWide: 28,
  contentMaxWidth: 400,
  sectionGap: 28,
  heroGap: 12,
  fieldGap: 20,
  cardPadding: 24,
  radiusLg: 20,
  radiusMd: 14,
  radiusButton: 12,
  inputMinHeight: 56,
  buttonMinHeight: 56,
  logoIconSize: 96,
  logoIconSizeSmall: 80,
} as const;

export const AuthTypography = {
  brand: { fontSize: 32, fontWeight: '800' as const, letterSpacing: -0.8 },
  portal: { fontSize: 18, fontWeight: '600' as const, letterSpacing: 0.2 },
  tagline: { fontSize: 11, fontWeight: '500' as const, letterSpacing: 1.2 },
  inputLabel: { fontSize: 15, fontWeight: '600' as const },
  input: { fontSize: 17, fontWeight: '400' as const },
  button: { fontSize: 17, fontWeight: '700' as const },
  helper: { fontSize: 15, lineHeight: 22 },
  error: { fontSize: 14, lineHeight: 20 },
} as const;
